
# externals
import typing_extensions as _tx

# internals
from brainhops.datamodel import transformations as _xforms
from brainhops.io.base.nifti import NiftiBasedParser
from brainhops.io.transformations.base.affines import RASToVoxel
from brainhops.io.transformations.base.fields import RASCoordinatesField
from brainhops.io.transformations.common.affines import NiftiRASToVoxel
from brainhops.io.transformations.common.fields import NiftiRASCoordinatesField


class SPMCoordinatesField(_xforms.Sequence, NiftiBasedParser):
    """Field of RAS coordinates.

    Transformations of this type are generated by the SPM software, and
    their filenames are often prefixed with `y_` or `iy_`.
    """

    @property
    def transformations(self) -> _tx.Tuple[
        _tx.Optional[RASToVoxel],
        _tx.Optional[RASCoordinatesField],
    ]:
        """The transformations that make up the sequence."""
        _transformations = getattr(self, "_transformations", None)
        if _transformations is not None:
            return _transformations
        return (
            NiftiRASToVoxel(image=self.image, header=self.header),
            NiftiRASCoordinatesField(image=self.image, header=self.header),
        )

    @transformations.setter
    def transformations(self, value: _tx.Tuple[
        _tx.Optional[RASToVoxel],
        _tx.Optional[RASCoordinatesField],
    ]) -> None:
        self._transformations = tuple(value)

    @property
    def ras2voxel(self) -> _tx.Optional[RASToVoxel]:
        """The RAS-to-voxel transformation."""
        xform = self.transformations[0]
        if xform is None:
            xform = NiftiRASToVoxel(image=self.image, header=self.header)
        return xform

    @property
    def rasfield(self) -> _tx.Optional[RASCoordinatesField]:
        """The field of RAS coordinates."""
        xform = self.transformations[1]
        if xform is None:
            xform = NiftiRASCoordinatesField(
                image=self.image, header=self.header)
        return xform

    @ras2voxel.setter
    def ras2voxel(self, value: RASToVoxel):
        self._transformations = (value, self.transformations[1])

    @rasfield.setter
    def rasfield(self, value: RASCoordinatesField):
        self._transformations = (self.transformations[0], value)
