"""SPM deformation fields, stored as `y_`/`iy_`-prefixed NIfTI files."""

# externals
import nibabel as nb
import numpy as np
import typing_extensions as tx
from bagof.magic import replace

# internals
from brainhops.datamodel import transformations as _xforms
from brainhops.datamodel._transformations.convert import converter
from brainhops.io.base._base import register_format
from brainhops.io.base.nifti import (
    _apply_like,
    _apply_overrides,
    _NiftiObject,
)
from brainhops.io.transformations.base import ConvertedFormat
from brainhops.io.transformations.base.affines import RASToVoxel
from brainhops.io.transformations.base.conversions import (
    apply_affine,
    split_field_chain,
    unrepresentable,
)
from brainhops.io.transformations.base.fields import (
    RASCoordinatesField,
    homogeneous_matrix,
)
from brainhops.io.transformations.nifti.affines import NiftiRASToVoxel
from brainhops.io.transformations.nifti.base import NiftiBasedTransformation
from brainhops.io.transformations.nifti.converters import (
    RAS,
    _check_coordinates,
)
from brainhops.io.transformations.nifti.fields import (
    NiftiRASCoordinatesField,
    ras_coordinates_nifti,
)


@register_format
class SpmCoordinatesField(
    ConvertedFormat, _xforms.ImmutableSequence, NiftiBasedTransformation
):
    """Field of RAS coordinates.

    Transformations of this type are generated by the SPM software, and
    their filenames are often prefixed with `y_` or `iy_`.

    The field is the
    [`ImmutableSequence`][brainhops.datamodel.transformations.ImmutableSequence]
    of two named slots, `ras2voxel` and `rasfield`: editing it in place
    raises `TypeError`. It maps RAS to RAS: a point is carried to the
    voxels of the field's grid, where the field holds the RAS position it
    maps to.

    It is written as SPM writes it: the RAS coordinates, as values, in a
    NIfTI file whose voxel-to-RAS affine is the inverse of `ras2voxel`.
    Another transformation is converted to it exactly, or not at all (see
    [`brainhops.io.transformations.nifti.converters`][]).
    """

    HINTS = ("spm",)

    PREFIXES: tx.ClassVar[tx.Tuple[str, ...]] = ("y_", "iy_")
    """
    SPM deformation fields are a plain NIfTI field plus a naming
    convention. The prefix is the only thing that distinguishes them
    from a generic field, and a parser that constrains the prefix is
    more specific than one that does not, so it wins ties.
    """

    @classmethod
    def _score_nibabel(cls, header: _NiftiObject) -> float:
        """
        float a NIfTI header as an SPM deformation field.

        Deliberately *identical* to `NiftiRASCoordinatesField`: on
        content alone the two are indistinguishable, and pretending
        otherwise would be inventing evidence. The `y_`/`iy_` prefix is
        the only real difference, and it decides the tie through
        `PREFIXES`, which ranks a constrained parser above an
        unconstrained one.
        """
        return NiftiRASCoordinatesField._score_nibabel(header)

    # The stored chain is a tuple, as `ImmutableSequence` declares it, so
    # the derived and the assigned chain are both immutable, and in-place
    # edits such as `del field[0]` are refused.

    @property
    def transformations(
        self,
    ) -> tx.Tuple[
        tx.Optional[RASToVoxel],
        tx.Optional[RASCoordinatesField],
    ]:
        """The transformations that make up the sequence."""
        _transformations = getattr(self, "_transformations", None)
        if _transformations is not None:
            return _transformations
        return (
            NiftiRASToVoxel(image=self.image, header=self.header),
            NiftiRASCoordinatesField(image=self.image, header=self.header),
        )

    @transformations.setter
    def transformations(
        self,
        value: tx.Tuple[
            tx.Optional[RASToVoxel],
            tx.Optional[RASCoordinatesField],
        ],
    ) -> None:
        # `None` is the inherited default, and means "derive them from
        # the NIfTI"; only a real sequence gets frozen into a tuple.
        self._transformations = None if value is None else tuple(value)

    @property
    def ras2voxel(self) -> tx.Optional[RASToVoxel]:
        """The RAS-to-voxel transformation."""
        xform = self.transformations[0]
        if xform is None:
            xform = NiftiRASToVoxel(image=self.image, header=self.header)
        return xform

    @property
    def rasfield(self) -> tx.Optional[RASCoordinatesField]:
        """The field of RAS coordinates."""
        xform = self.transformations[1]
        if xform is None:
            xform = NiftiRASCoordinatesField(
                image=self.image, header=self.header
            )
        return xform

    @ras2voxel.setter
    def ras2voxel(self, value: RASToVoxel) -> None:
        self._transformations = (value, self.transformations[1])

    @rasfield.setter
    def rasfield(self, value: RASCoordinatesField) -> None:
        self._transformations = (self.transformations[0], value)

    # --- writing ------------------------------------------------------

    def to_nibabel(
        self, like: tx.Any = None, **overrides
    ) -> tx.Union[nb.Nifti1Image, nb.Nifti2Image]:
        """
        Build the `nibabel` image that encodes this deformation field.

        The coordinates of `rasfield`, as values, become the data array,
        with the `VECTOR` (1007) intent code and the intent name
        `"Mapping"` that SPM writes. The voxel-to-RAS affine of the grid
        is the inverse of `ras2voxel`.

        When `like` is given, non-encoding header fields are copied from
        it. Keyword arguments override header fields last.
        """
        what = "An SPM deformation field"
        # The inverse of a `NiftiRASToVoxel` read from a header is that
        # header's affine itself, rather than an inverse of its inverse.
        vox2ras = homogeneous_matrix(self.ras2voxel.inverse(), what, ndim=3)
        # SPM stores sampled coordinates.
        image = ras_coordinates_nifti(
            self.rasfield.to(coeff=False).data, vox2ras
        )
        _apply_like(image, like)
        _apply_overrides(image, overrides)
        return image


# ----------------------------------------------------------------------
#   CONVERTERS
# ----------------------------------------------------------------------


@converter(_xforms.DisplacementField, SpmCoordinatesField)
@converter(_xforms.Sequence, SpmCoordinatesField)
@converter
def _(t: _xforms.CoordinatesField, **kwargs) -> SpmCoordinatesField:
    # Exactly, or raise: an affine from RAS to a grid, then one field of
    # coordinates on that grid, sampled as NIfTI stores it, followed by an
    # affine into RAS. A field of displacements is refused there, with the
    # reason.
    ras2voxel, field, voxel2ras = _spm_coordinates(t)
    chain = (
        RASToVoxel(matrix=ras2voxel[:-1]),
        RASCoordinatesField(field=apply_affine(voxel2ras, field.field)),
    )
    return SpmCoordinatesField(transformations=chain, **kwargs)


@converter
def _(t: SpmCoordinatesField, **kwargs) -> SpmCoordinatesField:
    # Within its own format, a field is copied with the changes asked for.
    return replace(t, **kwargs) if kwargs else t


def _spm_coordinates(t: _xforms.Transformation) -> tuple:
    """
    `t` as an SPM deformation field, or the reason it is not.

    Returns `(ras2voxel, field, voxel2ras)`: the homogeneous affine from
    RAS to the grid of the field, the field of coordinates, and the affine
    its coordinates are carried into RAS by.
    """
    cls = SpmCoordinatesField
    ras2voxel, field, voxel2ras = split_field_chain(t, RAS, RAS, cls)
    _check_coordinates(field, t, cls)
    if np.linalg.det(ras2voxel) == 0.0:
        raise unrepresentable(
            t,
            cls,
            "the affine before its field is singular, and SPM stores the "
            "grid of the field by its inverse.",
        )
    return ras2voxel, field, voxel2ras
