"""SPM deformation fields, stored as `y_`/`iy_`-prefixed NIfTI files."""

# externals
import typing_extensions as tx

# internals
from brainhops.datamodel import transformations as _xforms
from brainhops.io.base._base import register_format
from brainhops.io.base.nifti import (
    _NiftiObject,
)
from brainhops.io.transformations.base.affines import RasToVoxel
from brainhops.io.transformations.base.fields import RasCoordinatesField
from brainhops.io.transformations.nifti.affines import NiftiRasToVoxel
from brainhops.io.transformations.nifti.base import NiftiBasedTransformation
from brainhops.io.transformations.nifti.fields import NiftiRasCoordinatesField


@register_format
class SpmCoordinatesField(_xforms.ImmutableSequence, NiftiBasedTransformation):
    """Field of RAS coordinates.

    Transformations of this type are generated by the SPM software, and
    their filenames are often prefixed with `y_` or `iy_`.

    The field is the
    [`ImmutableSequence`][brainhops.datamodel.transformations.ImmutableSequence]
    of two named slots, `ras2voxel` and `rasfield`: editing it in place
    raises `TypeError`.
    """

    HINTS = ("spm",)

    PREFIXES: tx.ClassVar[tx.Tuple[str, ...]] = ("y_", "iy_")
    """
    SPM deformation fields are a plain NIfTI field plus a naming
    convention. The prefix is the only thing that distinguishes them
    from a generic field, and a parser that constrains the prefix is
    more specific than one that does not, so it wins ties.
    """

    @classmethod
    def _score_nibabel(cls, header: _NiftiObject) -> float:
        """
        float a NIfTI header as an SPM deformation field.

        Deliberately *identical* to `NiftiRasCoordinatesField`: on
        content alone the two are indistinguishable, and pretending
        otherwise would be inventing evidence. The `y_`/`iy_` prefix is
        the only real difference, and it decides the tie through
        `PREFIXES`, which ranks a constrained parser above an
        unconstrained one.
        """
        return NiftiRasCoordinatesField._score_nibabel(header)

    # The stored chain is a tuple, as `ImmutableSequence` declares it, so
    # the derived and the assigned chain are both immutable, and in-place
    # edits such as `del field[0]` are refused.

    @property
    def transformations(
        self,
    ) -> tx.Tuple[
        tx.Optional[RasToVoxel],
        tx.Optional[RasCoordinatesField],
    ]:
        """The transformations that make up the sequence."""
        _transformations = getattr(self, "_transformations", None)
        if _transformations is not None:
            return _transformations
        return (
            NiftiRasToVoxel(image=self.image, header=self.header),
            NiftiRasCoordinatesField(image=self.image, header=self.header),
        )

    @transformations.setter
    def transformations(
        self,
        value: tx.Tuple[
            tx.Optional[RasToVoxel],
            tx.Optional[RasCoordinatesField],
        ],
    ) -> None:
        # `None` is the inherited default, and means "derive them from
        # the NIfTI"; only a real sequence gets frozen into a tuple.
        self._transformations = None if value is None else tuple(value)

    @property
    def ras2voxel(self) -> tx.Optional[RasToVoxel]:
        """The RAS-to-voxel transformation."""
        xform = self.transformations[0]
        if xform is None:
            xform = NiftiRasToVoxel(image=self.image, header=self.header)
        return xform

    @property
    def rasfield(self) -> tx.Optional[RasCoordinatesField]:
        """The field of RAS coordinates."""
        xform = self.transformations[1]
        if xform is None:
            xform = NiftiRasCoordinatesField(
                image=self.image, header=self.header
            )
        return xform

    @ras2voxel.setter
    def ras2voxel(self, value: RasToVoxel) -> None:
        self._transformations = (value, self.transformations[1])

    @rasfield.setter
    def rasfield(self, value: RasCoordinatesField) -> None:
        self._transformations = (self.transformations[0], value)
